### ISSUE TITLE
Add OI shopping list into f-droid

### ISSUE THREAD

**Issue by asd-and-Rizzo** [openintents/shoppinglist#14]
Also, I'd like you app to be on f-droid https://f-droid.org/forums/topic/oi-shopping-list/#post-14208 . Wanted to suggest to put it here. 
I do not know why other people like f-droid, but I do most search of apps on f-droid before doing any search on Google Play.

**Comment by TPS** [comment]
+1 :+1:

**Comment by TPS** [comment]
@friedger If you interested in this, especially to _keep_ this updated in F-droid, maybe you'd be interested in the related issues @  https://github.com/openintents/notepad/issues/16, https://github.com/openintents/safe/issues/19, & https://github.com/openintents/filemanager/issues/57? Many F-droid users would be thankful!

**Comment by friedger** [comment]
For now,  I am waiting for gitlab.com to finish my fork of the metadata...

**Comment by friedger** [comment]
Started at https://gitlab.com/friedger/fdroiddata/blob/master/metadata/org.openintents.shopping.txt

**Comment by friedger** [comment]
ERROR: Found unknown maven repo 'https://github.com/openintents/public-mvn-repo/raw/master/releases' at build.gradle

We can move this to jitpack.io for the distribution library


ERROR: Found usual supect 'google.*play.*services' at line 20 at ShoppingListExtGlass/build.gradle

This is not part of the build flavor `tstore` and will be totally removed in the next release.

ERROR: Found usual supect 'google.*play.*services' at line 35 at ShoppingListWear/build.gradle
ERROR: Found usual supect 'google.*play.*services' at line 25 at ShoppingList/build.gradle

These are not part of the build flavor `tstore` and should be accepted by fdroid

ERROR: Found unknown maven repo '../myorepository' at ShoppingList/build.gradle

This is not part of the build flavor `tstore`, however, this can't be proven. Not sure how to resolve that. Any ideas @TPS @asd-and-Rizzo ?

**Comment by TPS** [comment]
I'm pretty much guessing, but I'm not sure _that_'s what it's complaining about....

Looking at the actual repo structure, shouldn't that actually be`../../myorepository`, _not_`../myorepository`?

Failing that, since the actual content is @`/myorepository/com/thalmic/myosdk/`(not 3 levels higher), could that be used instead, either as a relative or absolute path?

**Comment by asd-and-Rizzo** [comment]
I am not Android developer. But I see errors regarding 'google.play.services'. I tried to find these on https://f-droid.org and https://f-droid.org/forums/ - no result. As I know fdroid apps cut from code directly depending on google.play.services. So may be try mock and build with dummy calls without dependency of google.play.services binaries if exists?

**Comment by friedger** [comment]
I managed to remove all non-foss dependencies. So a pull request is on its way: https://gitlab.com/fdroid/fdroiddata/merge_requests/1260

**Comment by TPS** [comment]
@friedger I suppose you can close this — https://f-droid.org/repository/browse/?fdid=org.openintents.shopping has been active since March 5!

& thanks. ☺:clap::bow:
