### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by asd-and-Rizzo** [openintents/shoppinglist#15]
I searched Donate button on site OI sites. Not found any. I like this app. What to like with some tip.

**Comment by friedger** [comment]
there is a temporary link http://openintents.org/~oi/contribute

**Comment by asd-and-Rizzo** [comment]
Thanks. It also searchable via "site:http://openintents.org/ donate", but no link form main page. Nor Donate nor Contribute.

**Comment by asd-and-Rizzo** [comment]
Hi, I made donation and got email

```
Dzmitry,
thank you for purchasing at OpenIntents.

Unfortunately, a license key could not be generated. Please provide
 - your customerId from menu "Settings" ->"License"
 - the product you want to purchase
 - the version code of the licensing scheme (usually 1)
Please send this information to support@openintents.org and we will send you the license key within 24h.

Thank you!

Regards,
The OpenIntents Team

www.openintents.biz
```

I hope this will be fixed for pure donates not related to purchasing.
