### ISSUE TITLE
Invisible text in autocomplete list

### ISSUE THREAD

**Issue by asd-and-Rizzo** [openintents/shoppinglist#16]
1. I had `Milk` in previous buys.

2. I type `Mi` 

Expected: Popup is shown with available items and I can read text of popup.

Actual: Popup is shown with available items, but text color is same of background, so I cannot read text and choose right item.

Value: 
There are many items which start same typing but continue different. E.g. food starting on `M` and `Milk` and `Milk for baby`. Having autocomplete is useful.

Notes: I tried all themes from settings, issue in all of them.

Device:

Issue on Android 5.0 Samsung Galaxy S5.  Seems 4.4 version  worked fine on this device.

APK installed is latest from Google Play.

**Comment by aperomsik** [comment]
Please try the pre-release version of OI Shopping List if you have not already. Among other UI changes, it moves new item entry to the action bar, where the colors are not affected by the active theme. Also by default the autocomplete is replaced by search on the fly within the current list, and you can directly interact with the items in the search results.

To install our build of the pre-release version you need to join our [OpenIntents App Users group](https://plus.google.com/communities/102097420123460267614) on Google+. Once you are a member you can go to [this page](https://play.google.com/apps/testing/org.openintents.shopping) to opt in to the pre-release/test version of OI Shopping List, and then it will be offered to you by Google Play.

(Or you could build from this repository, but to install your own build you would have to first uninstall ours. If you choose this route, be sure to back up your data first-- one list at a time, in HandyShopper format, using OI Convert CSV.)

**Comment by asd-and-Rizzo** [comment]
Thanks. I will try this in near future.

**Comment by asd-and-Rizzo** [comment]
Work well on pre-release
