### ISSUE TITLE
Hard to read Add button  in default theme

### ISSUE THREAD

**Issue by rpoulin** [openintents/shoppinglist#21]
Hi,
Just upgraded my phone to Samsung S5 and found that the button at the bottom right corner of the screen has a background color that is too close in contrast to the text on the button. I saw white on white, yellow on pale grey and yellow on white.  Very difficult to read it.  Could someone have a look and tell me where to fix it?  I tried to find the style sheet for it but couldn't even find the app folder on this new phone.  

All of the themes fail in the same manner except for the classic theme.

**Comment by aperomsik** [comment]
Please try the prerelease version, or build your own apk from the current master branch. The Add button is no longer used by default... instead, items are added via action bar.

To install the pre-release version you need to join our [OpenIntents App Users group](https://plus.google.com/communities/102097420123460267614) on Google+. Once you are a member you can go to [this page](https://play.google.com/apps/testing/org.openintents.shopping) to opt in to the pre-release/test version of OI Shopping List, and then it will be offered to you by Google Play.

We look forward to your feedback on the new version.
