### ISSUE TITLE
Sorting list by a certain tag only causes app to crash permanently

### ISSUE THREAD

**Issue by PBZzz** [openintents/shoppinglist#24]
Hi, I have 2 lists in OI Shopping List app.  The Grocery one has Tags set up for stores.  If I select to display a filtered list by a specific tag (like Costco, or Trader Joe's), it crashes the app.  Permanently.  I can't get it to come back up ("Unfortunately OI Shopping List has stopped"), even if I restart the phone, clear the cache, etc.  My only way back is to uninstall the app, restart the phone, reinstall the app, and import the backup of my lists.  This problem happened several times on my Motorola Droid Razr Maxx HD, and now it is also doing it on my Samsung Galaxy Note 4.  I would go to another app, but this one (when it works) is practically perfect.  I have it working again, and thought maybe if I add Stores under the Stores button instead of under Tags, I could sort it that way.  But I can't find a way to enter a store.  If I click on Stores, it says "There are no stores set for this list".  But no method to add stores for a list is provided.  Even when you add or edit a list item, there is no field to add a Store list (which is why I tag the stores instead).  At least I can sort the entire list by Tags, then alphabetical, so it groups them, more or less.  I sure wish someone would come up with a fix for this!  Suggestions?

**Comment by aperomsik** [comment]
Sounds like you may be experiencing the same issue as #18 . We have a fix but I don't think we have released a beta which includes it yet. You might want to sign up for the prerelease anyway, following instructions on issue #16. That way when we do push a new beta to Play Store you will get it automatically. 

Regarding adding stores, you can long-press an item and choose Stores... from the item's context menu. This brings up the stores dialog which lets you mark which stores have each item, and also has an Add button to add stores.

**Comment by PBZzz** [comment]
Thank you so much! I tried the Stores fix, and it worked! You might want to ads that to the FAQ's, since I looked there before bothering you.
I am already a tester, so hopefully they will push the beta to me when it comes out.
Thanks for your fast and effective help!
Patty B
On Nov 1, 2015 6:27 PM, Aaron Peromsik <notifications@github.com> wrote:Sounds like you may be experiencing the same issue as #18 . We have a fix but I don't think we have released a beta which includes it yet. You might want to sign up for the prerelease anyway, following instructions on issue #16. That way when we do push a new beta to Play Store you will get it automatically. 

Regarding adding stores, you can long-press an item and choose Stores... from the item's context menu. This brings up the stores dialog which lets you mark which stores have each item, and also has an Add button to add stores.

**Comment by friedger** [comment]
fixed
