### ISSUE TITLE
OI Shopping List/Convert CSV for Windows Phone development

### ISSUE THREAD

**Issue by varenorn** [openintents/shoppinglist#25]
I have been using an Android 2.2 phone for a while.  But more recently, I have been using a Windows 8.1 phone.

The app I most use is the Android based OI Shopping List.  After a lot of searching around for alternative shopping list apps for the Windows phone, it transpired that the most appropriate shopping list app for my Windows phone was OI Shopping List: https://www.microsoft.com/en-gb/store/apps/oi-shopping-list/9nblggh0jq9z

However, there is one bit of "functionality" that allowed me to integrate data to OI Shopping List on my Android to my desktop PC: OI Convert CSV.  Its HandyShopper format is particularly 'data rich', which allows data such as shops and shop prices to be imported.  In contrast, the Windows phone version only imports/exports just a bare check list of items either to the One/SkyDrive or via e-mail.

I've been trying to find the repository that is most appropriate for the Windows Phone version of OI Shopping List.  However, I can't find it.  In particular, I can't find a repository for what could be the Windows Phone version of OI Convert CSV.  Does a repository exist for this even?

So if somebody could point me in the right direction for this, it would be appreciated.  Also, pointers to information on how to develop the Windows Phone version of OI Shopping List would be appreciated, especially using a Linux PC!

(Apologies if this is an inappropriate place to put this message.  If I have submitted this request for information in the wrong place, please show me where I should be posting such a query.)

**Comment by friedger** [comment]
The repository is here: https://github.com/openintents/shoppinglist_winphone

**Comment by friedger** [comment]
Sorry, there is no version of OI Convert CSV for win. However, the export / import is programmed directly into shopping list.

**Comment by varenorn** [comment]
Just to say that I had a quick look to find out how to develop C# for Windows Phone on Linux.  I managed to find information at http://stackoverflow.com/questions/8463669/is-it-possible-to-develop-windows-phone-7-apps-without-a-windows-machine

The information states that I should really have a Microsoft Windows 7 environment plus a Microsoft development environment.  I have neither and both need to be paid for.  Though I have Java knowledge, I will need to learn C#.

Therefore, it looks like I won't be going further with this (at least in the near future)!!

I'll just leave this comment open just in case anybody wants to comment on this or take this further (or an admin can close this "issue" if so desired).
