### ISSUE TITLE
Radio button does not reflect shopping mode

### ISSUE THREAD

**Issue by stebeh** [openintents/shoppinglist#49]
Using OI shopping 2.1.3 (commit 9b420290daafacb64b8aba5d3b163d23db7a369f) the radio button shown in attached image often does not reflect the mode correctly (shopping vs pick items).

How to reproduce: create a shopping list, click the bars menu top left, click shopping, click pick items, switch between both a couple of times. The list view transitions to selected mode but the radio button does not follow, i.e. stays on the wrong selection, not the one tapped.

This is on Android 7.0 API 24 in emulator. Maybe it is the emulator. I don't have a real device with Android 7.0 to try.

![pic 5](https://user-images.githubusercontent.com/9285448/34033577-1296da2c-e17b-11e7-8de5-baf9642631f6.png)

**Comment by Online77777** [comment]
Danke ;).

Am Di., 13. Nov. 2018, 10:27 hat stebeh <notifications@github.com>
geschrieben:

**Comment by friedger** [comment]
fixed in #62
