### ISSUE TITLE
Shopping state not preserved when app is stopped during search

### ISSUE THREAD

**Issue by stebeh** [openintents/shoppinglist#59]
How to reproduce: make sure you are using layout "search bar at top". Make sure you are in mode "Shopping". Now click the (+) Search symbol in top bar. Type something. Now rotate the device. Result: you have exited search, but are now in "Pick items" mode. Expected: should return to mode before search, which was "shopping".

This occurred to me several times when opening large apps and Android reclaimed memory. After restarting OI Shopping, I then had to switch mode back manually, which is a bit annoying.

Working on a fix.

**Comment by friedger** [comment]
fixed in #60
